name: dropdown_timepicker_package_example
description: "Dropdown Timepicker in Flutter package example project for Flutter developers."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dropdown_timepicker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
