name: dropdown_timepicker
description: "A robust dropdown-based time picker for Flutter with 12/24-hour support and form validation."
version: 1.0.0
homepage: https://robertrobinson.in/
repository: https://github.com/Robertrobinson777/dropdown_timepicker
issue_tracker: https://github.com/Robertrobinson777/dropdown_timepicker/issues

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
